### ISSUE TITLE
tdk isim sözlüğü

### ISSUE THREAD

**Issue by davut5** [tayfun/sozluk#2]
merhabalar. Acaba tdk isim sözlüğünün json formatı yada bir yedeği var mı sizde. yada farklı bir 
isim ve anlamları vs olan bir veritabanı örneği..???
cevabınızı bekliyorum teşekkürler...

**Comment by tayfun** [comment]
DynamoDB veritabaninda tum sozluk verisi. Proje kaynak kodunu indirip bakabilirsiniz. AWS uzerinde calistirirsaniz http://blog.tayfunsen.com/sozluk/ gibi bir sayfaniz olacaktir.
